// <auto-generated />
using ApiFutbolTorneo.Service;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiFutbolTorneo.Migrations
{
    [DbContext(typeof(FutbolDBContext))]
    [Migration("20210813214020_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiFutbolTorneo.Entities.FutbolDBEquipos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipo")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("equipo")
                        .IsUnique()
                        .HasFilter("[equipo] IS NOT NULL");

                    b.ToTable("FutbolDBEquipos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            color = "celeste",
                            equipo = "Arsenal"
                        },
                        new
                        {
                            id = 2,
                            color = "rojo",
                            equipo = "Independiente"
                        },
                        new
                        {
                            id = 3,
                            color = "verde y rojo",
                            equipo = "Banfield"
                        },
                        new
                        {
                            id = 4,
                            color = "rojo y azul",
                            equipo = "Tigre"
                        },
                        new
                        {
                            id = 5,
                            color = "celeste y blanco",
                            equipo = "Racing"
                        },
                        new
                        {
                            id = 6,
                            color = "rojo y blanco",
                            equipo = "River"
                        });
                });

            modelBuilder.Entity("ApiFutbolTorneo.Entities.FutbolDBJugadoras", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dni")
                        .HasColumnType("int");

                    b.Property<string>("equipojugando")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("dni")
                        .IsUnique();

                    b.ToTable("FutbolDBJugadoras");

                    b.HasData(
                        new
                        {
                            id = 1,
                            apellido = "Suarez",
                            dni = 40640921,
                            equipojugando = "Arsenal",
                            nombre = "Carla"
                        },
                        new
                        {
                            id = 2,
                            apellido = "Gutierrez",
                            dni = 41640822,
                            equipojugando = "Arsenal",
                            nombre = "Martina"
                        },
                        new
                        {
                            id = 3,
                            apellido = "Souza",
                            dni = 42680923,
                            equipojugando = "Arsenal",
                            nombre = "Marta"
                        },
                        new
                        {
                            id = 4,
                            apellido = "Perez",
                            dni = 43640924,
                            equipojugando = "Arsenal",
                            nombre = "Natalia"
                        },
                        new
                        {
                            id = 5,
                            apellido = "Alvarez",
                            dni = 44640925,
                            equipojugando = "Arsenal",
                            nombre = "Rocio"
                        },
                        new
                        {
                            id = 6,
                            apellido = "Fole",
                            dni = 45640926,
                            equipojugando = "Arsenal",
                            nombre = "Micaela"
                        },
                        new
                        {
                            id = 7,
                            apellido = "Gonzalez",
                            dni = 46640927,
                            equipojugando = "Arsenal",
                            nombre = "Antonela"
                        },
                        new
                        {
                            id = 8,
                            apellido = "Ramirez",
                            dni = 47640928,
                            equipojugando = "Arsenal",
                            nombre = "Beatriz"
                        },
                        new
                        {
                            id = 9,
                            apellido = "Jacinto",
                            dni = 48640929,
                            equipojugando = "Arsenal",
                            nombre = "Gabriela"
                        },
                        new
                        {
                            id = 10,
                            apellido = "Suarez",
                            dni = 49640928,
                            equipojugando = "Arsenal",
                            nombre = "Tamara"
                        },
                        new
                        {
                            id = 11,
                            apellido = "Martinez",
                            dni = 41040929,
                            equipojugando = "Arsenal",
                            nombre = "Belen"
                        },
                        new
                        {
                            id = 12,
                            apellido = "Perez",
                            dni = 41140922,
                            equipojugando = "Independiente",
                            nombre = "Marina"
                        },
                        new
                        {
                            id = 13,
                            apellido = "Alvarez",
                            dni = 94120923,
                            equipojugando = "Independiente",
                            nombre = "Martina"
                        },
                        new
                        {
                            id = 14,
                            apellido = "Souza",
                            dni = 41340924,
                            equipojugando = "Independiente",
                            nombre = "Eugenia"
                        },
                        new
                        {
                            id = 15,
                            apellido = "Gonzalez",
                            dni = 41440925,
                            equipojugando = "Independiente",
                            nombre = "Oriana"
                        },
                        new
                        {
                            id = 16,
                            apellido = "Alvarez",
                            dni = 41540926,
                            equipojugando = "Independiente",
                            nombre = "Marina"
                        },
                        new
                        {
                            id = 17,
                            apellido = "Angel",
                            dni = 41640977,
                            equipojugando = "Independiente",
                            nombre = "Marta"
                        },
                        new
                        {
                            id = 18,
                            apellido = "Maritini",
                            dni = 41740928,
                            equipojugando = "Independiente",
                            nombre = "Romina"
                        },
                        new
                        {
                            id = 19,
                            apellido = "Capelletti",
                            dni = 41940929,
                            equipojugando = "Independiente",
                            nombre = "Juliana"
                        },
                        new
                        {
                            id = 20,
                            apellido = "Suarez",
                            dni = 42040928,
                            equipojugando = "Banfield",
                            nombre = "Martina"
                        },
                        new
                        {
                            id = 21,
                            apellido = "Gutierrez",
                            dni = 42140929,
                            equipojugando = "Banfield",
                            nombre = "Cecilia"
                        },
                        new
                        {
                            id = 22,
                            apellido = "Espinonza",
                            dni = 42240921,
                            equipojugando = "Banfield",
                            nombre = "Marta"
                        },
                        new
                        {
                            id = 23,
                            apellido = "Tarantini",
                            dni = 42340922,
                            equipojugando = "Banfield",
                            nombre = "Julie"
                        },
                        new
                        {
                            id = 25,
                            apellido = "Fole",
                            dni = 42540924,
                            equipojugando = "Banfield",
                            nombre = "Micaela"
                        },
                        new
                        {
                            id = 26,
                            apellido = "Gonzalez",
                            dni = 42640965,
                            equipojugando = "Banfield",
                            nombre = "Antonela"
                        },
                        new
                        {
                            id = 27,
                            apellido = "Ramirez",
                            dni = 42740926,
                            equipojugando = "Banfield",
                            nombre = "Abril"
                        },
                        new
                        {
                            id = 28,
                            apellido = "Jacinto",
                            dni = 42840927,
                            equipojugando = "Banfield",
                            nombre = "Gabriela"
                        },
                        new
                        {
                            id = 29,
                            apellido = "Suarez",
                            dni = 42940928,
                            equipojugando = "Banfield",
                            nombre = "Tamara"
                        },
                        new
                        {
                            id = 30,
                            apellido = "Martinez",
                            dni = 43040929,
                            equipojugando = "Banfield",
                            nombre = "Belen"
                        },
                        new
                        {
                            id = 31,
                            apellido = "Espinoza",
                            dni = 43140900,
                            equipojugando = "Banfield",
                            nombre = "Violeta"
                        },
                        new
                        {
                            id = 32,
                            apellido = "Godoy",
                            dni = 43240921,
                            equipojugando = "Racing",
                            nombre = "Catalina"
                        },
                        new
                        {
                            id = 33,
                            apellido = "Perez",
                            dni = 43340922,
                            equipojugando = "Racing",
                            nombre = "Martina"
                        },
                        new
                        {
                            id = 34,
                            apellido = "Alvarez",
                            dni = 34640923,
                            equipojugando = "Racing",
                            nombre = "Marta"
                        },
                        new
                        {
                            id = 35,
                            apellido = "Perez",
                            dni = 43540924,
                            equipojugando = "Racing",
                            nombre = "Natalia"
                        },
                        new
                        {
                            id = 36,
                            apellido = "Garcia",
                            dni = 43640925,
                            equipojugando = "Racing",
                            nombre = "Guadalupe"
                        },
                        new
                        {
                            id = 37,
                            apellido = "Fole",
                            dni = 43740926,
                            equipojugando = "Racing",
                            nombre = "Oriana"
                        },
                        new
                        {
                            id = 38,
                            apellido = "Gonzalez",
                            dni = 43840927,
                            equipojugando = "Racing",
                            nombre = "Mariana"
                        },
                        new
                        {
                            id = 39,
                            apellido = "Naupari",
                            dni = 43940928,
                            equipojugando = "Racing",
                            nombre = "Patricia"
                        },
                        new
                        {
                            id = 41,
                            apellido = "Suarez",
                            dni = 44140920,
                            equipojugando = "River",
                            nombre = "Carla"
                        },
                        new
                        {
                            id = 42,
                            apellido = "Gutierrez",
                            dni = 44240920,
                            equipojugando = "River",
                            nombre = "Martina"
                        },
                        new
                        {
                            id = 43,
                            apellido = "Souza",
                            dni = 44340920,
                            equipojugando = "River",
                            nombre = "Marta"
                        },
                        new
                        {
                            id = 44,
                            apellido = "Perez",
                            dni = 44440921,
                            equipojugando = "River",
                            nombre = "Natalia"
                        },
                        new
                        {
                            id = 45,
                            apellido = "Alvarez",
                            dni = 44540922,
                            equipojugando = "River",
                            nombre = "Rocio"
                        },
                        new
                        {
                            id = 46,
                            apellido = "Fole",
                            dni = 44640923,
                            equipojugando = "River",
                            nombre = "Micaela"
                        },
                        new
                        {
                            id = 47,
                            apellido = "Gonzalez",
                            dni = 44740924,
                            equipojugando = "River",
                            nombre = "Antonela"
                        },
                        new
                        {
                            id = 48,
                            apellido = "Ramirez",
                            dni = 44840925,
                            equipojugando = "River",
                            nombre = "Diana"
                        },
                        new
                        {
                            id = 49,
                            apellido = "Jacinto",
                            dni = 44940927,
                            equipojugando = "River",
                            nombre = "Gabriela"
                        },
                        new
                        {
                            id = 50,
                            apellido = "Suarez",
                            dni = 45040956,
                            equipojugando = "River",
                            nombre = "Tamara"
                        },
                        new
                        {
                            id = 51,
                            apellido = "Martinez",
                            dni = 45140929,
                            equipojugando = "River",
                            nombre = "Belen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
